Final_Project_PRN/StudentManagementWebApp/Models/Student.cs
using System;
using System.Collections.Generic;

namespace StudentManagementWebApp.Models;

public partial class Student
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public int? Age { get; set; }

    public string? Address { get; set; }

    public double? Avg { get; set; }

    public int? AdmissionalYear { get; set; }

    public string? Majors { get; set; }

    public string? Type { get; set; }
}

Final_Project_PRN/StudentManagementWebApp/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StudentManagementWebApp.Repository;
using StudentManagementWebApp.Models;
using Microsoft.EntityFrameworkCore;

namespace StudentsManagementWebApp.Controllers
{
    public class StudentsController : Controller
    {
        IStudentRepository studentRepository = null;
        public StudentsController() => studentRepository = new StudentRepository();
        // GET: StudentsController
        public ActionResult Index(string sortOrder)
        {
            var context = new StudentsContext();
            ViewBag.IdSortParm = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewBag.AvgSortParm = sortOrder == "Avg" ? "avg_desc" : "Avg";
            ViewBag.AgeSortParm = sortOrder == "Age" ? "age_desc" : "Age";
            ViewBag.YearSortParm = sortOrder == "Year" ? "year_desc" : "Year";
            ViewBag.NameSortParm = sortOrder == "Name" ? "name_desc" : "Name";

            var students = from s in context.Students
                           select s;
            switch (sortOrder)
            {
                case "id_desc":
                    students = students.OrderByDescending(s => s.Id);
                    break;
                case "Avg":
                    students = students.OrderBy(s => s.Avg);
                    break;
                case "avg_desc":
                    students = students.OrderByDescending(s => s.Avg);
                    break;
                case "Age":
                    students = students.OrderBy(s => s.Age);
                    break;
                case "age_desc":
                    students = students.OrderByDescending(s => s.Age);
                    break;
                case "Year":
                    students = students.OrderBy(s => s.AdmissionalYear);
                    break;
                case "year_desc":
                    students = students.OrderByDescending(s => s.AdmissionalYear);
                    break;
                case "Name":
                    students = students.OrderBy(s => s.Name);
                    break;
                case "name_desc":
                    students = students.OrderByDescending(s => s.Name);
                    break;
                default:
                    students = students.OrderBy(s => s.Id);
                    break;
            }
            return View(students.ToList());
        }

        public ActionResult SearchByName(string name)
        {
            var context = new StudentsContext();
            var students = from s in context.Students
                           where s.Name.Contains(name)
                           select s;
            return View("Index", students);
        }

        public ActionResult SearchByMajor(string major)
        {
            var context = new StudentsContext();
            var students = from s in context.Students
                           where s.Majors.Contains(major)
                           select s;
            return View("Index", students);
        }

        public ActionResult SearchByType(string type)
        {
            var context = new StudentsContext();
            var students = from s in context.Students
                           where s.Type.Contains(type)
                           select s;
            return View("Index", students);
        }

        // GET: StudentsController/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = studentRepository.GetStudentByID(id.Value);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // GET: StudentsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: StudentsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Student student)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    studentRepository.InsertStudent(student);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View(student);
            }
        }

        // GET: StudentsController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = studentRepository.GetStudentByID(id.Value);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: StudentsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Student student)
        {
            try
            {
                if (id != student.Id)
                {
                    return NotFound();
                }
                if (ModelState.IsValid)
                {
                    studentRepository.UpdateStudent(student);
                }
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View();
            }
        }

        // GET: StudentsController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var student = studentRepository.GetStudentByID(id.Value);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: StudentsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                studentRepository.DeleteStudent(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return View();
            }
        }
    }
}

Final_Project_PRN/StudentManagementWebApp/Views/Students/Create.cshtml
@model StudentManagementWebApp.Models.Student

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create new student</h1>

<h4>@ViewBag.Message</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avg" class="control-label"></label>
                <input asp-for="Avg" class="form-control" />
                <span asp-validation-for="Avg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdmissionalYear" class="control-label"></label>
                <input asp-for="AdmissionalYear" class="form-control" />
                <span asp-validation-for="AdmissionalYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Majors" class="control-label"></label>
                <input asp-for="Majors" class="form-control" />
                <span asp-validation-for="Majors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Final_Project_PRN/StudentManagementWebApp/Views/Students/Delete.cshtml
@model StudentManagementWebApp.Models.Student

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Avg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Avg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdmissionalYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdmissionalYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Majors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Majors)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Final_Project_PRN/StudentManagementWebApp/Views/Students/Details.cshtml
@model StudentManagementWebApp.Models.Student

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Avg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Avg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdmissionalYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdmissionalYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Majors)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Majors)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id  }) |
    <a asp-action="Index">Back to List</a>
</div>

Final_Project_PRN/StudentManagementWebApp/Views/Students/Edit.cshtml
@model StudentManagementWebApp.Models.Student

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avg" class="control-label"></label>
                <input asp-for="Avg" class="form-control" />
                <span asp-validation-for="Avg" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AdmissionalYear" class="control-label"></label>
                <input asp-for="AdmissionalYear" class="form-control" />
                <span asp-validation-for="AdmissionalYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Majors" class="control-label"></label>
                <input asp-for="Majors" class="form-control" />
                <span asp-validation-for="Majors" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Final_Project_PRN/StudentManagementWebApp/Views/Students/Index.cshtml
@model IEnumerable<StudentManagementWebApp.Models.Student>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    a {
        color: black;
        text-decoration: none;
    }

    .button {
        background-color: orange;
        border: none;
        border-radius: 3px;
        padding: 2.5px 13px;
    }

    form {
        font-size: 16px;
    }
</style>

<h1 style="color: darkblue; text-align: center; margin: 30px 0px;">Students Management</h1>
<h3 style="color: mediumblue; margin: 20px 40px;">Search by</h3>
<div style="display: flex; justify-content: space-around;">
    <form asp-controller="Students" asp-action="SearchByName" method="get">
        <p>
            Name :  <input type="text" name="name" />
            <input type="submit" value="Search" class="button" />
        </p>
    </form>
    <form asp-controller="Students" asp-action="SearchByMajor" method="get">
        <p>
            Major :  <input type="text" name="major" />
            <input type="submit" value="Search" class="button" />
        </p>
    </form>
    <form asp-controller="Students" asp-action="SearchByType" method="get">
        <p>
            Type :  <input type="text" name="type" />
            <input type="submit" value="Search" class="button" />
        </p>
    </form>
</div>
<div style="display: flex; justify-content: space-between;">
    <p>
        <a asp-action="Create" style="text-decoration: none; font-size: 24px; color: blue">Create New</a>
    </p>
    <div style="float: right; margin-right: 40px;">
        <a asp-action="Index" style="text-decoration: none; font-size: 20px; color: blue">List all students</a>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.ActionLink("Id", "Index", new { sortOrder = ViewBag.IdSortParm })
            </th>
            <th>
                @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm })
            </th>
            <th>
                @Html.ActionLink("Age", "Index", new { sortOrder = ViewBag.AgeSortParm })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.ActionLink("Avg", "Index", new { sortOrder = ViewBag.AvgSortParm })
            </th>
            <th>
                @Html.ActionLink("Year", "Index", new { sortOrder = ViewBag.YearSortParm })
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Majors)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Avg)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AdmissionalYear)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Majors)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Type)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new {  id=item.Id  }) |
                    @Html.ActionLink("Details", "Details", new {  id=item.Id  }) |
                    @Html.ActionLink("Delete", "Delete", new {  id=item.Id  })
                </td>
            </tr>
        }

    </tbody>
</table>